# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-05-24 06:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiv1', '0002_auto_20200524_1143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduledexam',
            name='is_appeared',
            field=models.BooleanField(default=False, max_length=1),
        ),
    ]
